---
- hosts: all
  name: Create backup on Staging Servers
  tasks:
   - name: Create IHISApps_Backup directory if unExists
     win_file:
      path: D:\IHISApps_Backup\
      state: directory 
   - name: Create IHISApps_Backup directory if unExists
     win_file:
      path: D:\IHISApps_Backup\ans_cdma_20210803.zip
      state: absent

   - name: Run specific file zip backup
     win_command: cmd.exe /c D:\Deployment\Scripts\zip.exe -r "D:\IHISApps_Backup\ans_cdma_config_20210803.zip" "D:\IHISApps\Staging2\CDMAssessment\AssessmentForm\web.config" "D:\IHISApps\Staging2\CDMAssessment\AssessmentWebService\web.config"
   
   - name: Run full zip backup
     win_command: cmd.exe /c D:\Deployment\Scripts\zip.exe -r "D:\IHISApps_Backup\ans_cdma_20210803.zip" "D:\IHISApps\Staging2\CDMAssessment"  -x "\*\Log?\\*"
     #     win_command: cmd.exe /c D:\Deployment\Scripts\zip.exe -r "D:\IHISApps_Backup\ans_cdma_20210803.zip" "D:\IHISApps\Staging2\CDMAssessment"

   - name: List backup file
     register: listout
     win_find:
      paths: D:\IHISApps_Backup\
      file_type: file
      patterns: ['ans*.zip']
      age: -3600
   - debug:
      msg: "{{item.filename}} with {{item.size}} bytes"
     loop: "{{listout.files}}"
