---
- hosts: all
  gather_facts: no
  tasks:
   - name: Test connection with dest host {{ dest_host }}  and port
     win_wait_for:
      host: "{{ dest_host }}"
      port: "{{ item }}"
      delay: 0
      timeout: 3
     with_items: "{{ listPorts }}"
